version: "3"
services:
  app:
    container_name: travel-server
    build: .
    ports:
      - "4941:4941"
    environment:
      - TRAVEL_DB_HOST
      - TRAVEL_DB_USER
      - TRAVEL_DB_PASSWORD
      - TRAVEL_DB_DATABASE
    restart: on-failure
    depends_on:
      - db

  db:
    container_name: travel-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'travelapp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

networks:
  default:
    driver: overlay
