version: "3"
services:
  app:
    container_name: travel-server
    build: .
    ports:
      - "4941:4941"
    environment:
      - TRAVEL_DB_HOST
      - TRAVEL_DB_USER
      - TRAVEL_DB_PASSWORD
      - TRAVEL_DB_DATABASE
    restart: on-failure
networks:
  default:
    driver: overlay
